### PR TITLE
Fixed html paths

### LINKED ISSUE #1: GH-Page can't access assets
GH-page is published on https://gfoidl-tests.github.io/Vue_Test/

```
Laden fehlgeschlagen für das <script> mit der Quelle "https://gfoidl-tests.github.io/assets/app.9b42bc89024cf1f6549b.js". Vue_Test:1:1
```
As can be seen it's the wrong url.
```diff
- https://gfoidl-tests.github.io/assets/app.9b42bc89024cf1f6549b.js
+ https://gfoidl-tests.github.io/Vue_Test/assets/app.9b42bc89024cf1f6549b.js
```

### PR DESCRIPTION
**Pull request by gfoidl**
Fixes https://github.com/gfoidl-Tests/Vue_Test/issues/1

### CODE REVIEW

File: src/ts/shims/asset-shim.d.ts [hunk 1]
```diff
@@ -0,0 +1,4 @@
+declare module "*.png" {
```
Comment (gfoidl) [inline src/ts/shims/asset-shim.d.ts:1]: For this PR it's not necessary, only when 
```ts
import img from "@img/calculator.png";
```
so TypeScript knows what to do.
